name: Deploy
on:
  push:
    branches: [master]
jobs:
  release:
    runs-on: self-hosted
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - name: Build
        run: |
          set GOOS=windows
          go build -o build/DiceGame_Windows.exe
          set GOOS=darwin
          go build -o build/DiceGame_Mac
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_id }}
          release_name: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
      - name: Upload Windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/DiceGame_Windows.exe
          asset_name: DiceGame_Windows.exe
          asset_content_type: application/octet-stream
      - name: Upload Mac
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/DiceGame_Mac
          asset_name: DiceGame_Mac
          asset_content_type: application/octet-stream
